---
- id: editorconfig-checker
  name: "Check .editorconfig rules"
  description: "`editorconfig-checker` is a tool to check if your files consider your .editorconfig-rules."
  entry: editorconfig-checker
  language: python
  types: [text]
  require_serial: true
- id: editorconfig-checker-system
  name: "Check .editorconfig rules"
  description: "Runs system executable of `editorconfig-checker` to lint text files according to `.editorconfig` rules"
  language: system
  entry: editorconfig-checker
  types: [text]
  require_serial: true
